mbh_sitederencontre_home:
  path:     /
  defaults:
    _controller: MBHSitederencontreBundle:Advert:index 


mbh_sitederencontre_profilcompleted:
  path:     /profilcompleted/{id}
  defaults: 
    _controller: MBHSitederencontreBundle:Advert:profilcompleted
  requirements:
    id: \d+ 


mbh_sitederencontre_view:
  path:     /profils/{page}
  defaults: 
    _controller: MBHSitederencontreBundle:Advert:view
    page:    1
  requirements:
    page: \d*
    

mbh_sitederencontre_monprofil:
  path:     /monprofil/{id}
  defaults: 
    _controller: MBHSitederencontreBundle:Advert:monprofil
  requirements:
    id: \d+


mbh_sitederencontre_edit:
  path:     /edit/{id}
  defaults: 
    _controller: MBHSitederencontreBundle:Advert:edit
  requirements:
    id: \d+

mbh_sitederencontre_imageprofile:
  path:     /monprofil/{id}/image
  defaults:
    _controller: MBHSitederencontreBundle:Advert:profileImage
  methods: post
  requirements:
    id: \d+